CREATE TABLE IF NOT EXISTS users (
    user_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login varchar(50) NOT NULL,
    email varchar(50) NOT NULL UNIQUE,
    name varchar(50),
    birthday date
);
CREATE TABLE IF NOT EXISTS friends (
    user_id int REFERENCES users(user_id) ON DELETE CASCADE,
    friend_id int REFERENCES users(user_id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, friend_id)
);
CREATE TABLE IF NOT EXISTS ratings (
    rating_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(30) NOT NULL UNIQUE
);
CREATE TABLE IF NOT EXISTS films (
    film_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(50) NOT NULL,
    description varchar(200),
    release_date date,
    duration int,
    rating_id int REFERENCES ratings(rating_id)
);
CREATE TABLE IF NOT EXISTS likes (
    film_id int REFERENCES films(film_id) ON DELETE CASCADE,
    user_id int REFERENCES users(user_id) ON DELETE CASCADE,
    PRIMARY KEY (film_id, user_id)
);
CREATE TABLE IF NOT EXISTS genres (
    genre_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(50) NOT NULL
);
CREATE TABLE IF NOT EXISTS films_genres (
    film_id int REFERENCES films(film_id) ON DELETE CASCADE,
    genre_id int REFERENCES genres(genre_id) ON DELETE CASCADE,
    PRIMARY KEY (film_id, genre_id)
);
-- Таблица отзывов
CREATE TABLE IF NOT EXISTS reviews (
    review_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content VARCHAR(1000) NOT NULL,
    is_positive BOOLEAN NOT NULL,
    user_id INT REFERENCES users(user_id) ON DELETE CASCADE,
    film_id INT REFERENCES films(film_id) ON DELETE CASCADE,
    useful INT DEFAULT 0
);
-- Таблица реакций на отзывы (лайки/дизлайки)
CREATE TABLE IF NOT EXISTS review_likes (
    review_id INT REFERENCES reviews(review_id) ON DELETE CASCADE,
    user_id INT REFERENCES users(user_id) ON DELETE CASCADE,
    is_like BOOLEAN NOT NULL, -- true = лайк, false = дизлайк
    PRIMARY KEY (review_id, user_id)
);
CREATE TABLE IF NOT EXISTS directors (
    director_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100) NOT NULL
);
CREATE TABLE IF NOT EXISTS films_directors (
    film_id int REFERENCES films(film_id) ON DELETE CASCADE,
    director_id int REFERENCES directors(director_id) ON DELETE CASCADE,
    PRIMARY KEY (film_id, director_id)
);
CREATE TABLE IF NOT EXISTS events (
    event_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_timestamp timestamp NOT NULL,
    user_id int REFERENCES users(user_id) ON DELETE CASCADE,
    event_type varchar(15) NOT NULL, -- LIKE, REVIEW или FRIEND
    operation varchar(15) NOT NULL, -- ADD, REMOVE или UPDATE
    entity_id int NOT NULL
);
