CREATE TABLE IF NOT EXISTS users (
    user_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login varchar(50) NOT NULL,
    email varchar(50) NOT NULL UNIQUE,
    name varchar(50),
    birthday date
);
CREATE TABLE IF NOT EXISTS friends (
    user_id int REFERENCES users(user_id),
    friend_id int REFERENCES users(user_id),
    PRIMARY KEY (user_id, friend_id)
);
CREATE TABLE IF NOT EXISTS ratings (
    rating_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(30) NOT NULL UNIQUE
);
CREATE TABLE IF NOT EXISTS films (
    film_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(50) NOT NULL,
    description varchar(200),
    release_date date,
    duration int,
    rating_id int REFERENCES ratings(rating_id)
);
CREATE TABLE IF NOT EXISTS likes (
    film_id int REFERENCES films(film_id),
    user_id int REFERENCES users(user_id),
    PRIMARY KEY (film_id, user_id)
);
CREATE TABLE IF NOT EXISTS genres (
    genre_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(50) NOT NULL
);
CREATE TABLE IF NOT EXISTS films_genres (
    film_id int REFERENCES films(film_id),
    genre_id int REFERENCES genres(genre_id),
    PRIMARY KEY (film_id, genre_id)
);